### PR TITLE
Update README with MacOS install instructions

### PR DESCRIPTION
**Pull request by marceloboeira**
Wait for homebrew/homebrew#48340 to be merged.

### CODE REVIEW

**Comment by greyblake** [comment]
Amazing! Thanks)

**Comment by marceloboeira** [comment]
@greyblake Now the problem is that the repository has less than 50 stars and 20 forks. What do you think about creating a private tap? I can do that.

**Comment by greyblake** [comment]
@marceloboeira I am not realy familiar with `brew`, I am Linux user. Does that mean, that brew instructions for installation will be hosted in this repo? If so, I am OK with this.

P.S. They can too high standards for our small community) Thanks for taking care of this :+1:

**Comment by marceloboeira** [comment]
@greyblake yeah, instead of hosting the install formula on the home-brew default repository, we use our own, it adds a step when installing but at least it would work haha.

**Comment by greyblake** [comment]
@marceloboeira Hi) Users can already install it with specifying a tap, right?

**Comment by marceloboeira** [comment]
@greyblake yes, I just did not have time to setup a private tap so far. Once I do I'll make this branch compatible again.

**Comment by greyblake** [comment]
@marceloboeira Cool! THanks)

**Comment by greyblake** [comment]
@marceloboeira Sorry, I am closing this one. https://github.com/Homebrew/legacy-homebrew/pull/48340 will never be merged ;-(

**Comment by marceloboeira** [comment]
@greyblake fair enough, I will create at some point a homebrew formula (independent) and add here the instructions. 

I have created one for bojack as well.
http://github.com/marceloboeira/homebrew-bojack

**Pull request closed without merging**
